In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

    age  gender   review education purchased
22   18  Female     Poor        PG       Yes
12   51    Male     Poor    School        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
8    65  Female  Average        UG        No

In [4]:
df = df.iloc[:,2:]

In [5]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)

In [7]:
X_train

     review education
31     Poor    School
43     Poor        PG
5   Average    School
30  Average        UG
9      Good        UG
45     Poor        PG
38     Good    School
16     Poor        UG
17     Poor        UG
26     Poor        PG
36     Good        UG
23     Good    School
1      Poor        UG
8   Average        UG
6      Good    School
47     Good        PG
24  Average        PG
40     Good    School
35     Poor    School
33     Good        PG
15     Poor        UG
41     Good        PG
10     Good        UG
32  Average        UG
21  Average        PG
39     Poor        PG
4   Average        UG
48     Good        UG
19     Poor        PG
46     Poor        PG
42     Good        PG
2      Good        PG
12     Poor    School
49     Good        UG
22     Poor        PG
20  Average    School
34  Average    School
13  Average    School
18     Good    School
37  Average        PG

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [9]:
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [10]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [11]:
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

In [12]:
X_train

     review education
31     Poor    School
43     Poor        PG
5   Average    School
30  Average        UG
9      Good        UG
45     Poor        PG
38     Good    School
16     Poor        UG
17     Poor        UG
26     Poor        PG
36     Good        UG
23     Good    School
1      Poor        UG
8   Average        UG
6      Good    School
47     Good        PG
24  Average        PG
40     Good    School
35     Poor    School
33     Good        PG
15     Poor        UG
41     Good        PG
10     Good        UG
32  Average        UG
21  Average        PG
39     Poor        PG
4   Average        UG
48     Good        UG
19     Poor        PG
46     Poor        PG
42     Good        PG
2      Good        PG
12     Poor    School
49     Good        UG
22     Poor        PG
20  Average    School
34  Average    School
13  Average    School
18     Good    School
37  Average        PG

In [13]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
le = LabelEncoder()

In [16]:
le.fit(y_train)

LabelEncoder()

In [17]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [18]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [19]:
y_train

array([1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1])